spring.application.name=weather

# Application properties
server.port=8080

openweather.api.url=http://api.openweathermap.org/data/2.5/weather?q={city}&appid={apikey}&units=metric


spring.config.import=optional:file:./secrets.properties